"""
Anchor albums for VinylSage ~ Starting with my favorite albums - N.K

Format: list of dicts with 'title', 'artist', 'year', 'wiki_title', and 'discogs_master_id'

Note: Master ids have only been set for the 15 anchor albums thus far.
"""




ANCHOR_ALBUMS = [


    # --- Original 15 Favorites ---
    {"title": "Led Zeppelin II", "artist": "Led Zeppelin", "year": 1969, "discogs_master_id": 4170},
    {"title": "Aja", "artist": "Steely Dan", "wiki_title": "Aja (album)", "year": 1977, "discogs_master_id": 14526},
    {"title": "Abraxas", "artist": "Santana", "wiki_title": "Abraxas (album)", "year": 1970, "discogs_master_id": 10620},
    {"title": "Sgt. Pepper's Lonely Hearts Club Band", "artist": "The Beatles", "year": 1967, "discogs_master_id": 23934},
    {"title": "Blizzard of Ozz", "artist": "Ozzy Osbourne", "year": 1980, "discogs_master_id": 26878},
    {"title": "A Night at the Opera", "artist": "Queen", "wiki_title": "A Night at the Opera (Queen album)", "year": 1975, "discogs_master_id": 27645},
    {"title": "Led Zeppelin IV", "artist": "Led Zeppelin", "wiki_title": "Led Zeppelin IV", "year": 1971, "discogs_master_id": 4172},
    {"title": "Can't Buy a Thrill", "artist": "Steely Dan", "year": 1972, "discogs_master_id": 44737},
    {"title": "One of These Nights", "artist": "Eagles", "wiki_title": "One of These Nights (Eagles album)", "year": 1975, "discogs_master_id": 18118},
    {"title": "The Wall", "artist": "Pink Floyd", "wiki_title": "The Wall", "year": 1979, "discogs_master_id": 17036},
    {"title": "Sheer Heart Attack", "artist": "Queen", "wiki_title": "Sheer Heart Attack", "year": 1974, "discogs_master_id": 27641},
    {"title": "Abbey Road", "artist": "The Beatles", "year": 1969, "discogs_master_id": 24047},
    {"title": "Supernatural", "artist": "Santana", "wiki_title": "Supernatural (Santana album)", "year": 1999, "discogs_master_id": 16539},
    {"title": "Rumours", "artist": "Fleetwood Mac", "wiki_title": "Rumours (album)", "year": 1977, "discogs_master_id": 13337},
    {"title": "Goodbye Yellow Brick Road", "artist": "Elton John", "wiki_title": "Goodbye Yellow Brick Road", "year": 1973, "discogs_master_id": 21690},
    {"title": "The Dark Side of the Moon", "artist": "Pink Floyd", "wiki_title": "The Dark Side of the Moon", "year": 1973, "discogs_master_id": 10362},

    # --- Expanded Collection ---
    {"title": "What's Going On", "artist": "Marvin Gaye", "wiki_title": "What's Going On (album)", "year": 1971},
    {"title": "London Calling", "artist": "The Clash", "year": 1979},
    {"title": "Born to Run", "artist": "Bruce Springsteen", "year": 1975},
    {"title": "Exile on Main St.", "artist": "The Rolling Stones", "wiki_title": "Exile on Main St.", "year": 1972},
    {"title": "Innervisions", "artist": "Stevie Wonder", "year": 1973},
    {"title": "Who's Next", "artist": "The Who", "year": 1971},
    {"title": "Songs in the Key of Life", "artist": "Stevie Wonder", "year": 1976},
    {"title": "Blue", "artist": "Joni Mitchell", "wiki_title": "Blue (Joni Mitchell album)", "year": 1971},
    {"title": "Tapestry", "artist": "Carole King", "wiki_title": "Tapestry (Carole King album)", "year": 1971},
    {"title": "Paranoid", "artist": "Black Sabbath", "wiki_title": "Paranoid (album)", "year": 1970},
    {"title": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "artist": "David Bowie", "wiki_title": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "year": 1972},
    {"title": "There's a Riot Goin' On", "artist": "Sly and the Family Stone", "wiki_title": "There's a Riot Goin' On", "year": 1971},
    {"title": "Blood on the Tracks", "artist": "Bob Dylan", "year": 1975},
    {"title": "Never Mind the Bollocks, Here's the Sex Pistols", "artist": "Sex Pistols", "wiki_title": "Never Mind the Bollocks, Here's the Sex Pistols", "year": 1977},
    {"title": "Hotel California", "artist": "Eagles", "wiki_title": "Hotel California (Eagles album)", "year": 1977},
    {"title": "Off the Wall", "artist": "Michael Jackson", "year": 1979},
    {"title": "Saturday Night Fever", "artist": "Bee Gees", "wiki_title": "Saturday Night Fever (soundtrack)", "year": 1977},
    {"title": "Bridge Over Troubled Water", "artist": "Simon & Garfunkel", "year": 1970},
    {"title": "After the Gold Rush", "artist": "Neil Young", "year": 1970},
    {"title": "Ramones", "artist": "Ramones", "wiki_title": "Ramones (album)", "year": 1976},
    {"title": "The Clash", "artist": "The Clash", "wiki_title": "The Clash (album)", "year": 1977},
    {"title": "Plastic Ono Band", "artist": "John Lennon", "wiki_title": "John Lennon/Plastic Ono Band", "year": 1970},
    {"title": "Superfly", "artist": "Curtis Mayfield", "wiki_title": "Super Fly (soundtrack)", "year": 1972},
    {"title": "Talking Book", "artist": "Stevie Wonder", "year": 1972},
    {"title": "This Year's Model", "artist": "Elvis Costello", "wiki_title": "This Year's Model", "year": 1978},
    {"title": "Sticky Fingers", "artist": "The Rolling Stones", "year": 1971},
    {"title": "Moondance", "artist": "Van Morrison", "year": 1970},
    {"title": "Van Halen", "artist": "Van Halen", "wiki_title": "Van Halen (album)", "year": 1978},
    {"title": "Horses", "artist": "Patti Smith", "wiki_title": "Horses (Patti Smith album)", "year": 1975},
    {"title": "Let It Be", "artist": "The Beatles", "wiki_title": "Let It Be (album)", "year": 1970},
    {"title": "Harvest", "artist": "Neil Young", "wiki_title": "Harvest (Neil Young album)", "year": 1972},
    {"title": "Machine Head", "artist": "Deep Purple", "wiki_title": "Machine Head (Deep Purple album)", "year": 1972},
    {"title": "Live at Leeds", "artist": "The Who", "year": 1970},
    {"title": "My Aim Is True", "artist": "Elvis Costello", "year": 1977},
    {"title": "Black Sabbath", "artist": "Black Sabbath", "wiki_title": "Black Sabbath (album)", "year": 1970},
    {"title": "Marquee Moon", "artist": "Television", "wiki_title": "Marquee Moon", "year": 1977},
    {"title": "Deja Vu", "artist": "Crosby, Stills, Nash & Young", "wiki_title": "Déjà vu (Crosby, Stills, Nash & Young album)", "year": 1970},
    {"title": "Low", "artist": "David Bowie", "wiki_title": "Low (David Bowie album)", "year": 1977},
    {"title": "All Things Must Pass", "artist": "George Harrison", "year": 1970},
    {"title": "Unknown Pleasures", "artist": "Joy Division", "year": 1979},
    {"title": "Live at the Fillmore East", "artist": "The Allman Brothers Band", "wiki_title": "Live at Fillmore East", "year": 1971},
    {"title": "Layla and Other Assorted Love Songs", "artist": "Derek and the Dominos", "year": 1970},
    {"title": "Imagine", "artist": "John Lennon", "wiki_title": "Imagine (John Lennon album)", "year": 1971},
    {"title": "Wish You Were Here", "artist": "Pink Floyd", "wiki_title": "Wish You Were Here (Pink Floyd album)", "year": 1975},
    {"title": "Physical Graffiti", "artist": "Led Zeppelin", "year": 1975},
    {"title": "Cosmo's Factory", "artist": "Creedence Clearwater Revival", "year": 1970},
    {"title": "Pearl", "artist": "Janis Joplin", "wiki_title": "Pearl (Janis Joplin album)", "year": 1971},
    {"title": "Captain Fantastic and the Brown Dirt Cowboy", "artist": "Elton John", "year": 1975},
    {"title": "American Beauty", "artist": "Grateful Dead", "wiki_title": "American Beauty (Grateful Dead album)", "year": 1970},
    {"title": "Fun House", "artist": "The Stooges", "wiki_title": "Fun House (The Stooges album)", "year": 1970},
    {"title": "Hunky Dory", "artist": "David Bowie", "year": 1971},
    {"title": "Exodus", "artist": "Bob Marley & the Wailers", "wiki_title": "Exodus (Bob Marley and the Wailers album)", "year": 1977},
    {"title": "Court and Spark", "artist": "Joni Mitchell", "year": 1974},
    {"title": "In Rock", "artist": "Deep Purple", "wiki_title": "Deep Purple in Rock", "year": 1970},
    {"title": "The Stranger", "artist": "Billy Joel", "wiki_title": "The Stranger (Billy Joel album)", "year": 1977},
    {"title": "Quadrophenia", "artist": "The Who", "year": 1973},
    {"title": "Toys in the Attic", "artist": "Aerosmith", "year": 1975},
    {"title": "Fragile", "artist": "Yes", "wiki_title": "Fragile (Yes album)", "year": 1971},
    {"title": "(Pronounced 'Leh-'nerd 'Skin-'nerd)", "artist": "Lynyrd Skynyrd", "wiki_title": "(Pronounced 'Leh-'nerd 'Skin-'nerd)", "year": 1973},
    {"title": "Aqualung", "artist": "Jethro Tull", "wiki_title": "Aqualung (album)", "year": 1971},
    {"title": "One Nation Under a Groove", "artist": "Funkadelic", "year": 1978},
    {"title": "Let's Get It On", "artist": "Marvin Gaye", "year": 1973},
    {"title": "Boston", "artist": "Boston", "wiki_title": "Boston (album)", "year": 1976},
    {"title": "Call Me", "artist": "Al Green", "wiki_title": "Call Me (Al Green album)", "year": 1973},
    {"title": "Mothership Connection", "artist": "Parliament", "year": 1975},
    {"title": "Frampton Comes Alive!", "artist": "Peter Frampton", "year": 1976},
    {"title": "Fulfillingness' First Finale", "artist": "Stevie Wonder", "year": 1974},
    {"title": "Catch a Fire", "artist": "Bob Marley & the Wailers", "year": 1973},
    {"title": "Honky Chateau", "artist": "Elton John", "year": 1972},
    {"title": "Heart Like a Wheel", "artist": "Linda Ronstadt", "year": 1974},
    {"title": "Rocks", "artist": "Aerosmith", "wiki_title": "Rocks (Aerosmith album)", "year": 1976},
    {"title": "Every Picture Tells a Story", "artist": "Rod Stewart", "year": 1971},
    {"title": "Sweet Baby James", "artist": "James Taylor", "year": 1970},
    {"title": "Bat Out of Hell", "artist": "Meat Loaf", "wiki_title": "Bat Out of Hell (album)", "year": 1977},
    {"title": "Bad Girls", "artist": "Donna Summer", "wiki_title": "Bad Girls (Donna Summer album)", "year": 1979},
    {"title": "Highway to Hell", "artist": "AC/DC", "year": 1979},
    {"title": "Parallel Lines", "artist": "Blondie", "year": 1978},
    {"title": "Trans-Europe Express", "artist": "Kraftwerk", "year": 1977},
    {"title": "Tea for the Tillerman", "artist": "Cat Stevens", "year": 1970},
    {"title": "Something/Anything?", "artist": "Todd Rundgren", "year": 1972},
    {"title": "Band on the Run", "artist": "Paul McCartney & Wings", "year": 1973},
    {"title": "3 + 3", "artist": "The Isley Brothers", "wiki_title": "3 + 3 (album)", "year": 1973},
    {"title": "Eat a Peach", "artist": "The Allman Brothers Band", "year": 1972},
    {"title": "Dreamboat Annie", "artist": "Heart", "year": 1975},
    {"title": "The Cars", "artist": "The Cars", "wiki_title": "The Cars (album)", "year": 1978},
    {"title": "Electric Warrior", "artist": "T. Rex", "year": 1971},
    {"title": "Darkness on the Edge of Town", "artist": "Bruce Springsteen", "year": 1978},
    {"title": "Running on Empty", "artist": "Jackson Browne", "year": 1977},
    {"title": "Alive!", "artist": "KISS", "wiki_title": "Alive! (Kiss album)", "year": 1975},
    {"title": "Fleetwood Mac", "artist": "Fleetwood Mac", "wiki_title": "Fleetwood Mac (album)", "year": 1975},
    {"title": "Rocket to Russia", "artist": "Ramones", "year": 1977},
    {"title": "New York Dolls", "artist": "New York Dolls", "wiki_title": "New York Dolls (album)", "year": 1973},
    {"title": "Damn the Torpedoes", "artist": "Tom Petty and the Heartbreakers", "year": 1979},
    {"title": "Rust Never Sleeps", "artist": "Neil Young & Crazy Horse", "year": 1979},
    {"title": "Close to You", "artist": "The Carpenters", "wiki_title": "Close to You (Carpenters album)", "year": 1970},
    {"title": "I'm Still in Love with You", "artist": "Al Green", "wiki_title": "I'm Still in Love with You (Al Green album)", "year": 1972},
    {"title": "Tumbleweed Connection", "artist": "Elton John", "year": 1970},
    {"title": "Workingman's Dead", "artist": "Grateful Dead", "year": 1970},
    {"title": "Maggot Brain", "artist": "Funkadelic", "year": 1971},
    {"title": "Close to the Edge", "artist": "Yes", "year": 1972},
    {"title": "The B-52's", "artist": "The B-52's", "wiki_title": "The B-52's (album)", "year": 1979},
    {"title": "Fresh", "artist": "Sly and the Family Stone", "wiki_title": "Fresh (Sly and the Family Stone album)", "year": 1973},
    {"title": "Houses of the Holy", "artist": "Led Zeppelin", "year": 1973},
    {"title": "Young, Gifted and Black", "artist": "Aretha Franklin", "wiki_title": "Young, Gifted and Black (Aretha Franklin album)", "year": 1972},
    {"title": "Burnin'", "artist": "Bob Marley and the Wailers", "wiki_title": "Burnin' (album)", "year": 1973},
    {"title": "L.A. Woman", "artist": "The Doors", "year": 1971},
    {"title": "Sad Wings of Destiny", "artist": "Judas Priest", "year": 1976},
    {"title": "That's the Way of the World", "artist": "Earth, Wind & Fire", "year": 1975},
    {"title": "Transformer", "artist": "Lou Reed", "year": 1972},
    {"title": "For Your Pleasure", "artist": "Roxy Music", "year": 1973},
    {"title": "Curtis", "artist": "Curtis Mayfield", "wiki_title": "Curtis (album)", "year": 1970},
    {"title": "There Goes Rhymin' Simon", "artist": "Paul Simon", "year": 1973},
    {"title": "Nightbirds", "artist": "LaBelle", "year": 1974},
    {"title": "Music of My Mind", "artist": "Stevie Wonder", "year": 1972},
    {"title": "Aladdin Sane", "artist": "David Bowie", "year": 1973},
    {"title": "Entertainment!", "artist": "Gang of Four", "year": 1979},
    {"title": "Outlandos d'Amour", "artist": "The Police", "year": 1978},
    {"title": "Talking Heads: 77", "artist": "Talking Heads", "year": 1977},
    {"title": "Pretzel Logic", "artist": "Steely Dan", "year": 1974},
    {"title": "The Basement Tapes", "artist": "Bob Dylan", "wiki_title": "The Basement Tapes", "year": 1975},
    {"title": "Master of Reality", "artist": "Black Sabbath", "year": 1971},
    {"title": "Some Girls", "artist": "The Rolling Stones", "wiki_title": "Some Girls (album)", "year": 1978},
    {"title": "Tubular Bells", "artist": "Mike Oldfield", "year": 1973},
    {"title": "Al Green Gets Next to You", "artist": "Al Green", "year": 1971},
    {"title": "The Wild, the Innocent & the E Street Shuffle", "artist": "Bruce Springsteen", "year": 1973},
    {"title": "Led Zeppelin III", "artist": "Led Zeppelin", "year": 1970},
    {"title": "Desire", "artist": "Bob Dylan", "wiki_title": "Desire (Bob Dylan album)", "year": 1976},
    {"title": "Grievous Angel", "artist": "Gram Parsons", "year": 1974},
    {"title": "Night Moves", "artist": "Bob Seger & the Silver Bullet Band", "wiki_title": "Night Moves (Bob Seger album)", "year": 1976},
    {"title": "461 Ocean Boulevard", "artist": "Eric Clapton", "year": 1974},
    {"title": "Station to Station", "artist": "David Bowie", "year": 1976},
    {"title": "More Songs About Buildings and Food", "artist": "Talking Heads", "year": 1978},
    {"title": "Queen II", "artist": "Queen", "year": 1974},
    {"title": "2112", "artist": "Rush", "wiki_title": "2112 (album)", "year": 1976},
    {"title": "Bryter Layter", "artist": "Nick Drake", "year": 1971},
    {"title": "Sail Away", "artist": "Randy Newman", "wiki_title": "Sail Away (Randy Newman album)", "year": 1972},
    {"title": "Look-Ka Py Py", "artist": "The Meters", "year": 1969},
    {"title": "Berlin", "artist": "Lou Reed", "wiki_title": "Berlin (Lou Reed album)", "year": 1973},
    {"title": "Tonight's the Night", "artist": "Neil Young", "wiki_title": "Tonight's the Night (Neil Young album)", "year": 1975},
    {"title": "Another Green World", "artist": "Brian Eno", "year": 1975},
    {"title": "Roxy Music", "artist": "Roxy Music", "wiki_title": "Roxy Music (album)", "year": 1972},
    {"title": "Back Stabbers", "artist": "The O'Jays", "year": 1972},
    {"title": "Pink Moon", "artist": "Nick Drake", "year": 1972},
    {"title": "Regatta de Blanc", "artist": "The Police", "year": 1979},
    {"title": "Autobahn", "artist": "Kraftwerk", "wiki_title": "Autobahn (album)", "year": 1974},
    {"title": "Late for the Sky", "artist": "Jackson Browne", "year": 1974},
    {"title": "52nd Street", "artist": "Billy Joel", "year": 1978},
    {"title": "Breakfast in America", "artist": "Supertramp", "year": 1979},
    {"title": "Animals", "artist": "Pink Floyd", "wiki_title": "Animals (Pink Floyd album)", "year": 1977},
    {"title": "Natty Dread", "artist": "Bob Marley & the Wailers", "year": 1974},
    {"title": "Selling England by the Pound", "artist": "Genesis", "year": 1973},
    {"title": "Raw Power", "artist": "Iggy and the Stooges", "year": 1973},
    {"title": "Fear of Music", "artist": "Talking Heads", "year": 1979},
    {"title": "Paul Simon", "artist": "Paul Simon", "wiki_title": "Paul Simon (album)", "year": 1972},
    {"title": "Slowhand", "artist": "Eric Clapton", "year": 1977},
    {"title": "Loaded", "artist": "The Velvet Underground", "wiki_title": "Loaded (The Velvet Underground album)", "year": 1970},
    {"title": "Country Life", "artist": "Roxy Music", "year": 1974},
    {"title": "The Pretender", "artist": "Jackson Browne", "wiki_title": "The Pretender (Jackson Browne album)", "year": 1976},
    {"title": "The Modern Lovers", "artist": "The Modern Lovers", "wiki_title": "The Modern Lovers (album)", "year": 1976},
    {"title": "Armed Forces", "artist": "Elvis Costello and the Attractions", "year": 1979},
    {"title": "Heroes", "artist": "David Bowie", "wiki_title": "\"Heroes\" (David Bowie album)", "year": 1977},
    {"title": "Here, My Dear", "artist": "Marvin Gaye", "year": 1978},
    {"title": "Radio City", "artist": "Big Star", "year": 1974},
    {"title": "Q: Are We Not Men? A: We Are Devo!", "artist": "Devo", "year": 1978},
    {"title": "Metal Box", "artist": "Public Image Ltd.", "year": 1979},
    {"title": "At Budokan", "artist": "Cheap Trick", "wiki_title": "Cheap Trick at Budokan", "year": 1978},
    {"title": "Pink Flag", "artist": "Wire", "year": 1977},
    {"title": "Thick as a Brick", "artist": "Jethro Tull", "year": 1972},
    {"title": "Back in the USA", "artist": "MC5", "year": 1970},
    {"title": "Band of Gypsys", "artist": "Jimi Hendrix", "year": 1970},
    {"title": "Here Come the Warm Jets", "artist": "Brian Eno", "year": 1974},
    {"title": "I Want to See the Bright Lights Tonight", "artist": "Richard and Linda Thompson", "year": 1974},
    {"title": "#1 Record", "artist": "Big Star", "year": 1972},
    {"title": "Bad Company", "artist": "Bad Company", "wiki_title": "Bad Company (album)", "year": 1974},
    {"title": "Tago Mago", "artist": "Can", "year": 1971},
    {"title": "Risqué", "artist": "Chic", "wiki_title": "Risqué (album)", "year": 1979},
    {"title": "12 Songs", "artist": "Randy Newman", "year": 1970},
    {"title": "Brothers and Sisters", "artist": "The Allman Brothers Band", "year": 1973},
    {"title": "In Color", "artist": "Cheap Trick", "wiki_title": "In Color (Cheap Trick album)", "year": 1977},
    {"title": "The World Is a Ghetto", "artist": "War", "wiki_title": "The World Is a Ghetto (album)", "year": 1972},
    {"title": "The Long Run", "artist": "Eagles", "year": 1979},
    {"title": "The Lamb Lies Down on Broadway", "artist": "Genesis", "year": 1974},
    {"title": "Mott", "artist": "Mott the Hoople", "wiki_title": "Mott (album)", "year": 1973},
    {"title": "Chicago V", "artist": "Chicago", "year": 1972},
    {"title": "Billion Dollar Babies", "artist": "Alice Cooper", "year": 1973},
    {"title": "Fly Like an Eagle", "artist": "Steve Miller Band", "year": 1976},
    {"title": "Destroyer", "artist": "KISS", "wiki_title": "Destroyer (Kiss album)", "year": 1976},
    {"title": "Suicide", "artist": "Suicide", "wiki_title": "Suicide (Suicide album)", "year": 1977},


]

