"""
Anchor albums for VinylSage ~ Starting with 15 of my favorite albums - N.K

Format: list of dicts with 'title' and 'artist' for Wikipedia lookup.
The 'wiki_title' field is optional - use it when the article title differs from simply the album name
"""



ANCHOR_ALBUMS = [
    {"title": "Led Zeppelin II", "artist": "Led Zeppelin"},
    {"title": "Aja", "artist": "Steely Dan", "wiki_title": "Aja (album)"},
    {"title": "Abraxas", "artist": "Santana", "wiki_title": "Abraxas (album)"},
    {"title": "Sgt. Pepper's Lonely Hearts Club Band", "artist": "The Beatles"},
    {"title": "Blizzard of Ozz", "artist": "Ozzy Osbourne"},
    {"title": "A Night at the Opera", "artist": "Queen", "wiki_title": "A Night at the Opera (Queen album)"},
    {"title": "Led Zeppelin IV", "artist": "Led Zeppelin", "wiki_title": "Led Zeppelin IV"},
    {"title": "Can't Buy a Thrill", "artist": "Steely Dan"},
    {"title": "One of These Nights", "artist": "Eagles", "wiki_title": "One of These Nights"},
    {"title": "The Wall", "artist": "Pink Floyd", "wiki_title": "The Wall"},
    {"title": "Sheer Heart Attack", "artist": "Queen"},
    {"title": "Abbey Road", "artist": "The Beatles"},
    {"title": "Supernatural", "artist": "Santana", "wiki_title": "Supernatural (Santana album)"},
    {"title": "Rumours", "artist": "Fleetwood Mac", "wiki_title": "Rumours (album)"},
    {"title": "Goodbye Yellow Brick Road", "artist": "Elton John"},
    {"title": "What's Going On", "artist": "Marvin Gaye"},
    {"title": "Dark Side Of The Moon", "artist": "Pink Floyd"},
    {"title": "London Calling", "artist": "The Clash"},
    {"title": "Born To Run", "artist": "Bruce Springsteen"},
    {"title": "Exile On Main Street", "artist": "Rolling Stones"},
    {"title": "Innervisions", "artist": "Stevie Wonder"},
    {"title": "Who's Next", "artist": "The Who"},
    {"title": "Led Zeppelin IV", "artist": "Led Zeppelin"},
    {"title": "Songs In The Key Of Life", "artist": "Stevie Wonder"},
    {"title": "Rumours", "artist": "Fleetwood Mac"},
    {"title": "Blue", "artist": "Joni Mitchell"},
    {"title": "Tapestry", "artist": "Carole King"},
    {"title": "Paranoid", "artist": "Black Sabbath"},
    {"title": "Ziggy Stardust & The Spiders From Mars", "artist": "David Bowie"},
    {"title": "There's A Riot Goin' On", "artist": "Sly And The Family Stone"},
    {"title": "The Wall", "artist": "Pink Floyd"},
    {"title": "Blood On The Tracks", "artist": "Bob Dylan"},
    {"title": "Never Mind The Bollocks Here's The Sex Pistols", "artist": "Sex Pistols"},
    {"title": "Hotel California", "artist": "The Eagles"},
    {"title": "Off the Wall", "artist": "Michael Jackson"},
    {"title": "Saturday Night Fever Soundtrack", "artist": "The Bee Gees"},
    {"title": "Bridge Over Troubled Water", "artist": "Simon & Garfunkel"},
    {"title": "After The Goldrush", "artist": "Neil Young"},
    {"title": "Ramones", "artist": "Ramones"},
    {"title": "Goodbye Yellow Brick Road", "artist": "Elton John"},
    {"title": "The Clash", "artist": "The Clash"},
    {"title": "Plastic Ono Band", "artist": "John Lennon"},
    {"title": "Superfly", "artist": "Curtis Mayfield"},
    {"title": "Talking Book", "artist": "Stevie Wonder"},
    {"title": "This Year's Model", "artist": "Elvis Costello & The Attractions"},
    {"title": "Sticky Fingers", "artist": "Rolling Stones"},
    {"title": "Moondance", "artist": "Van Morrison"},
    {"title": "A Night At The Opera", "artist": "Queen"},
    {"title": "Van Halen", "artist": "Van Halen"},
    {"title": "Horses", "artist": "Patti Smith"},
    {"title": "Let It Be", "artist": "The Beatles"},
    {"title": "Harvest", "artist": "Neil Young"},
    {"title": "Machine Head", "artist": "Deep Purple"},
    {"title": "Live at Leeds", "artist": "The Who"},
    {"title": "My Aim Is True", "artist": "Elvis Costello"},
    {"title": "Black Sabbath", "artist": "Black Sabbath"},
    {"title": "Marquee Moon", "artist": "Television"},
    {"title": "Déjà vu", "artist": "Crosby, Stills, Nash & Young"},
    {"title": "Low", "artist": "David Bowie"},
    {"title": "All Things Must Pass", "artist": "George Harrison"},
    {"title": "Unknown Pleasures", "artist": "Joy Division"},
    {"title": "Live at the Fillmore East", "artist": "The Allman Brothers Band"},
    {"title": "Layla And Other Assorted Love Songs", "artist": "Derek & The Dominos"},
    {"title": "Imagine", "artist": "John Lennon"},
    {"title": "Wish You Were Here", "artist": "Pink Floyd"},
    {"title": "Physical Graffiti", "artist": "Led Zeppelin"},
    {"title": "Abraxas", "artist": "Santana"},
    {"title": "Cosmo's Factory", "artist": "Creedence Clearwater Revival"},
    {"title": "Pearl", "artist": "Janis Joplin"},
    {"title": "Captain Fantastic & The Brown Dirt Cowboy", "artist": "Elton John"},
    {"title": "American Beauty", "artist": "Grateful Dead"},
    {"title": "Fun House", "artist": "Iggy Pop & the Stooges"},
    {"title": "Hunky Dory", "artist": "David Bowie"},
    {"title": "Exodus", "artist": "Bob Marley & the Wailers"},
    {"title": "Court and Spark", "artist": "Joni Mitchell"},
    {"title": "In Rock", "artist": "Deep Purple"},
    {"title": "The Stranger", "artist": "Billy Joel"},
    {"title": "Quadrophenia", "artist": "The Who"},
    {"title": "Toys In The Attic", "artist": "Aerosmith"},
    {"title": "Fragile", "artist": "Yes"},
    {"title": "Pronounced Leh'-nerd Skin-'nerd", "artist": "Lynyrd Skynyrd"},
    {"title": "Aqualung", "artist": "Jethro Tull"},
    {"title": "One Nation Under The Groove", "artist": "Funkadelic"},
    {"title": "Let's Get It On", "artist": "Marvin Gaye"},
    {"title": "Aja", "artist": "Steely Dan"},
    {"title": "Boston", "artist": "Boston"},
    {"title": "Call Me", "artist": "Al Green"},
    {"title": "Mothership Connection", "artist": "Parliament"},
    {"title": "Frampton Comes Alive", "artist": "Peter Frampton"},
    {"title": "Fullingness First Finale", "artist": "Stevie Wonder"},
    {"title": "Catch A Fire", "artist": "Bob Marley & The Wailers"},
    {"title": "Honky Chateau", "artist": "Elton John"},
    {"title": "Heart Like A Wheel", "artist": "Linda Ronstadt"},
    {"title": "Rocks", "artist": "Aerosmith"},
    {"title": "Every Picture Tells A Story", "artist": "Rod Stewart"},
    {"title": "Sweet Baby James", "artist": "James Taylor"},
    {"title": "Bat Out Of Hell", "artist": "Meat Loaf"},
    {"title": "Bad Girls", "artist": "Donna Summer"},
    {"title": "Highway To Hell", "artist": "AC/DC"},
    {"title": "Parallel Lines", "artist": "Blondie"},
    {"title": "Trans-Europe Express", "artist": "Kraftwerk"},
    {"title": "Tea For The Tillerman", "artist": "Cat Stevens"},
    {"title": "Something/Anything", "artist": "Todd Rundgren"},
    {"title": "Band On The Run", "artist": "Paul McCartney & Wings"},
    {"title": "3+3", "artist": "The Isley Brothers"},
    {"title": "Eat A Peach", "artist": "Allman Brothers Band"},
    {"title": "Dreamboat Annie", "artist": "Heart"},
    {"title": "The Cars", "artist": "The Cars"},
    {"title": "Electric Warrior", "artist": "T-Rex"},
    {"title": "Darkness On The Edge Of Town", "artist": "Bruce Springsteen"},
    {"title": "Running On Empty", "artist": "Jackson Browne"},
    {"title": "Alive!", "artist": "KISS"},
    {"title": "Fleetwood Mac", "artist": "Fleetwood Mac"},
    {"title": "Rocket To Russia", "artist": "Ramones"},
    {"title": "New York Dolls", "artist": "New York Dolls"},
    {"title": "Damn The Torpedoes", "artist": "Tom Petty & the Heartbreakers"},
    {"title": "Rust Never Sleeps", "artist": "Neil Young & Crazy Horse"},
    {"title": "Spinners", "artist": "The Spinners"},
    {"title": "Close To You", "artist": "The Carpenters"},
    {"title": "I'm Still In Love With You", "artist": "Al Green"},
    {"title": "Tumbleweed Connection", "artist": "Elton John"},
    {"title": "Workingman's Dead", "artist": "Grateful Dead"},
    {"title": "Maggot Brain", "artist": "Funkadelic"},
    {"title": "Close To The Edge", "artist": "Yes"},
    {"title": "The B-52's", "artist": "The B-52's"},
    {"title": "Fresh", "artist": "Sly and the Family Stone"},
    {"title": "Houses Of The Holy", "artist": "Led Zeppelin"},
    {"title": "Young, Gifted & Black", "artist": "Aretha Franklin"},
    {"title": "Burnin'", "artist": "Bob Marley and the Wailers"},
    {"title": "L.A. Woman", "artist": "The Doors"},
    {"title": "Sad Wings of Destiny", "artist": "Judas Priest"},
    {"title": "That's the Way of the World", "artist": "Earth, Wind, & Fire"},
    {"title": "Transformer", "artist": "Lou Reed"},
    {"title": "For Your Pleasure", "artist": "Roxy Music"},
    {"title": "Can't Get Enough", "artist": "Barry White"},
    {"title": "Curtis", "artist": "Curtis Mayfield"},
    {"title": "There Goes Rhymin' Simon", "artist": "Paul Simon"},
    {"title": "Nightbirds", "artist": "Labelle"},
    {"title": "Music of My Mind", "artist": "Stevie Wonder"},
    {"title": "Aladdin Sane", "artist": "David Bowie"},
    {"title": "Entertainment!", "artist": "Gang of Four"},
    {"title": "Outlandos D'Amour", "artist": "The Police"},
    {"title": "Talking Heads: 77", "artist": "Talking Heads"},
    {"title": "Pretzel Logic", "artist": "Steely Dan"},
    {"title": "The Basement Tapes", "artist": "Bob Dylan and the Band"},
    {"title": "Master Of Reality", "artist": "Black Sabbath"},
    {"title": "Some Girls", "artist": "Rolling Stones"},
    {"title": "Tubular Bells", "artist": "Mike Oldfield"},
    {"title": "Al Green Gets Next to You", "artist": "Al Green"},
    {"title": "Sheer Heart Attack", "artist": "Queen"},
    {"title": "The Wild, the Innocent and the E Street Shuffle", "artist": "Bruce Springsteen"},
    {"title": "Led Zeppelin III", "artist": "Led Zeppelin"},
    {"title": "Desire", "artist": "Bob Dylan"},
    {"title": "Grievous Angel", "artist": "Gram Parsons"},
    {"title": "Night Moves", "artist": "Bob Seger & the Silver Bullet Band"},
    {"title": "461 Ocean Boulevard", "artist": "Eric Clapton"},
    {"title": "Station to Station", "artist": "David Bowie"},
    {"title": "More Songs About Buildings and Food", "artist": "Talking Heads"},
    {"title": "Queen II", "artist": "Queen"},
    {"title": "2112", "artist": "Rush"},
    {"title": "Bryter Layter", "artist": "Nick Drake"},
    {"title": "Sail Away", "artist": "Randy Newman"},
    {"title": "Look-Ka Py Py", "artist": "The Meters"},
    {"title": "Berlin", "artist": "Lou Reed"},
    {"title": "Tonight's the Night", "artist": "Neil Young"},
    {"title": "Another Green World", "artist": "Brian Eno"},
    {"title": "Roxy Music", "artist": "Roxy Music"},
    {"title": "Back Stabbers", "artist": "The O'Jays"},
    {"title": "Pink Moon", "artist": "Nick Drake"},
    {"title": "Reggatta de Blanc", "artist": "The Police"},
    {"title": "Autobahn", "artist": "Kraftwerk"},
    {"title": "Late for the Sky", "artist": "Jackson Browne"},
    {"title": "52nd Street", "artist": "Billy Joel"},
    {"title": "Breakfast In America", "artist": "Supertramp"},
    {"title": "Animals", "artist": "Pink Floyd"},
    {"title": "Natty Dread", "artist": "Bob Marley & The Wailers"},
    {"title": "Selling England By The Pound", "artist": "Genesis"},
    {"title": "Raw Power", "artist": "Iggy And The Stooges"},
    {"title": "Fear of Music", "artist": "Talking Heads"},
    {"title": "Paul Simon", "artist": "Paul Simon"},
    {"title": "Slowhand", "artist": "Eric Clapton"},
    {"title": "Loaded", "artist": "The Velvet Underground"},
    {"title": "Country Life", "artist": "Roxy Music"},
    {"title": "The Pretender", "artist": "Jackson Browne"},
    {"title": "Modern Lovers", "artist": "Modern Lovers"},
    {"title": "Can't Buy a Thrill", "artist": "Steely Dan"},
    {"title": "Armed Forces", "artist": "Elvis Costello and the Attractions"},
    {"title": "Heroes", "artist": "David Bowie"},
    {"title": "Here, My Dear", "artist": "Marvin Gaye"},
    {"title": "Radio City", "artist": "Big Star"},
    {"title": "Q: Are We Not Men? A: We Are Devo!", "artist": "Devo"},
    {"title": "Metal Box", "artist": "Public Image Ltd."},
    {"title": "At Budokan", "artist": "Cheap Trick"},
    {"title": "Pink Flag", "artist": "Wire"},
    {"title": "Thick As A Brick", "artist": "Jethro Tull"},
    {"title": "Back In The USA", "artist": "MC5"},
    {"title": "Band Of Gypsys", "artist": "Jimi Hendrix"},
    {"title": "Here Come the Warm Jets", "artist": "Brian Eno"},
    {"title": "I Want to See the Bright Lights Tonight", "artist": "Richard and Linda Thompson"},
    {"title": "#1 Record", "artist": "Big Star"},
    {"title": "Bad Company", "artist": "Bad Company"},
    {"title": "Tago Mago", "artist": "Can"},
    {"title": "Risque", "artist": "Chic"},
    {"title": "12 Songs", "artist": "Randy Newman"},
    {"title": "Brothers And Sisters", "artist": "Allmans Brothers Band"},
    {"title": "In Color", "artist": "Cheap Trick"},
    {"title": "The World Is a Ghetto", "artist": "War"},
    {"title": "The Long Run", "artist": "The Eagles"},
    {"title": "The Lamb Lies Down On Broadway", "artist": "Genesis"},
    {"title": "Mott", "artist": "Mott the Hoople"},
    {"title": "Chicago V", "artist": "Chicago"},
    {"title": "Billion Dollar Babies", "artist": "Alice Cooper"},
    {"title": "Fly Like An Eagle", "artist": "Steve Miller Band"},
    {"title": "Destroyer", "artist": "KISS"},
    {"title": "Suicide", "artist": "Suicide"},

]
