"""
Anchor albums for VinylSage ~ Starting with my favorite albums - N.K

Format: list of dicts with 'title' and 'artist' for Wikipedia lookup.
The 'wiki_title' field is optional - use it when the article title differs
from simply the album name (disambiguation, special characters, etc.)
"""

ANCHOR_ALBUMS = [
    

    # --- Original 15 Favorites ---
    {"title": "Led Zeppelin II", "artist": "Led Zeppelin"},
    {"title": "Aja", "artist": "Steely Dan", "wiki_title": "Aja (album)"},
    {"title": "Abraxas", "artist": "Santana", "wiki_title": "Abraxas (album)"},
    {"title": "Sgt. Pepper's Lonely Hearts Club Band", "artist": "The Beatles"},
    {"title": "Blizzard of Ozz", "artist": "Ozzy Osbourne"},
    {"title": "A Night at the Opera", "artist": "Queen", "wiki_title": "A Night at the Opera (Queen album)"},
    {"title": "Led Zeppelin IV", "artist": "Led Zeppelin", "wiki_title": "Led Zeppelin IV"},
    {"title": "Can't Buy a Thrill", "artist": "Steely Dan"},
    {"title": "One of These Nights", "artist": "Eagles", "wiki_title": "One of These Nights (Eagles album)"},
    {"title": "The Wall", "artist": "Pink Floyd", "wiki_title": "The Wall"},
    {"title": "Sheer Heart Attack", "artist": "Queen", "wiki_title": "Sheer Heart Attack"},
    {"title": "Abbey Road", "artist": "The Beatles"},
    {"title": "Supernatural", "artist": "Santana", "wiki_title": "Supernatural (Santana album)"},
    {"title": "Rumours", "artist": "Fleetwood Mac", "wiki_title": "Rumours (album)"},
    {"title": "Goodbye Yellow Brick Road", "artist": "Elton John", "wiki_title": "Goodbye Yellow Brick Road"},

    # --- Expanded Collection ---
    {"title": "What's Going On", "artist": "Marvin Gaye", "wiki_title": "What's Going On (album)"},
    {"title": "The Dark Side of the Moon", "artist": "Pink Floyd", "wiki_title": "The Dark Side of the Moon"},
    {"title": "London Calling", "artist": "The Clash"},
    {"title": "Born to Run", "artist": "Bruce Springsteen"},
    {"title": "Exile on Main St.", "artist": "The Rolling Stones", "wiki_title": "Exile on Main St."},
    {"title": "Innervisions", "artist": "Stevie Wonder"},
    {"title": "Who's Next", "artist": "The Who"},
    {"title": "Songs in the Key of Life", "artist": "Stevie Wonder"},
    {"title": "Blue", "artist": "Joni Mitchell", "wiki_title": "Blue (Joni Mitchell album)"},
    {"title": "Tapestry", "artist": "Carole King", "wiki_title": "Tapestry (Carole King album)"},
    {"title": "Paranoid", "artist": "Black Sabbath", "wiki_title": "Paranoid (album)"},
    {"title": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "artist": "David Bowie", "wiki_title": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars"},
    {"title": "There's a Riot Goin' On", "artist": "Sly and the Family Stone", "wiki_title": "There's a Riot Goin' On"},
    {"title": "Blood on the Tracks", "artist": "Bob Dylan"},
    {"title": "Never Mind the Bollocks, Here's the Sex Pistols", "artist": "Sex Pistols", "wiki_title": "Never Mind the Bollocks, Here's the Sex Pistols"},
    {"title": "Hotel California", "artist": "Eagles", "wiki_title": "Hotel California (Eagles album)"},
    {"title": "Off the Wall", "artist": "Michael Jackson"},
    {"title": "Saturday Night Fever", "artist": "Bee Gees", "wiki_title": "Saturday Night Fever (soundtrack)"},
    {"title": "Bridge Over Troubled Water", "artist": "Simon & Garfunkel"},
    {"title": "After the Gold Rush", "artist": "Neil Young"},
    {"title": "Ramones", "artist": "Ramones", "wiki_title": "Ramones (album)"},
    {"title": "The Clash", "artist": "The Clash", "wiki_title": "The Clash (album)"},
    {"title": "Plastic Ono Band", "artist": "John Lennon", "wiki_title": "John Lennon/Plastic Ono Band"},
    {"title": "Superfly", "artist": "Curtis Mayfield", "wiki_title": "Super Fly (soundtrack)"},
    {"title": "Talking Book", "artist": "Stevie Wonder"},
    {"title": "This Year's Model", "artist": "Elvis Costello", "wiki_title": "This Year's Model"},
    {"title": "Sticky Fingers", "artist": "The Rolling Stones"},
    {"title": "Moondance", "artist": "Van Morrison"},
    {"title": "Van Halen", "artist": "Van Halen", "wiki_title": "Van Halen (album)"},
    {"title": "Horses", "artist": "Patti Smith", "wiki_title": "Horses (Patti Smith album)"},
    {"title": "Let It Be", "artist": "The Beatles", "wiki_title": "Let It Be (album)"},
    {"title": "Harvest", "artist": "Neil Young", "wiki_title": "Harvest (Neil Young album)"},
    {"title": "Machine Head", "artist": "Deep Purple", "wiki_title": "Machine Head (Deep Purple album)"},
    {"title": "Live at Leeds", "artist": "The Who"},
    {"title": "My Aim Is True", "artist": "Elvis Costello"},
    {"title": "Black Sabbath", "artist": "Black Sabbath", "wiki_title": "Black Sabbath (album)"},
    {"title": "Marquee Moon", "artist": "Television", "wiki_title": "Marquee Moon"},
    {"title": "Deja Vu", "artist": "Crosby, Stills, Nash & Young", "wiki_title": "Déjà vu (Crosby, Stills, Nash & Young album)"},
    {"title": "Low", "artist": "David Bowie", "wiki_title": "Low (David Bowie album)"},
    {"title": "All Things Must Pass", "artist": "George Harrison"},
    {"title": "Unknown Pleasures", "artist": "Joy Division"},
    {"title": "Live at the Fillmore East", "artist": "The Allman Brothers Band", "wiki_title": "Live at Fillmore East"},
    {"title": "Layla and Other Assorted Love Songs", "artist": "Derek and the Dominos"},
    {"title": "Imagine", "artist": "John Lennon", "wiki_title": "Imagine (John Lennon album)"},
    {"title": "Wish You Were Here", "artist": "Pink Floyd", "wiki_title": "Wish You Were Here (Pink Floyd album)"},
    {"title": "Physical Graffiti", "artist": "Led Zeppelin"},
    {"title": "Cosmo's Factory", "artist": "Creedence Clearwater Revival"},
    {"title": "Pearl", "artist": "Janis Joplin", "wiki_title": "Pearl (Janis Joplin album)"},
    {"title": "Captain Fantastic and the Brown Dirt Cowboy", "artist": "Elton John"},
    {"title": "American Beauty", "artist": "Grateful Dead", "wiki_title": "American Beauty (Grateful Dead album)"},
    {"title": "Fun House", "artist": "The Stooges", "wiki_title": "Fun House (The Stooges album)"},
    {"title": "Hunky Dory", "artist": "David Bowie"},
    {"title": "Exodus", "artist": "Bob Marley & the Wailers", "wiki_title": "Exodus (Bob Marley and the Wailers album)"},
    {"title": "Court and Spark", "artist": "Joni Mitchell"},
    {"title": "In Rock", "artist": "Deep Purple", "wiki_title": "Deep Purple in Rock"},
    {"title": "The Stranger", "artist": "Billy Joel", "wiki_title": "The Stranger (Billy Joel album)"},
    {"title": "Quadrophenia", "artist": "The Who"},
    {"title": "Toys in the Attic", "artist": "Aerosmith"},
    {"title": "Fragile", "artist": "Yes", "wiki_title": "Fragile (Yes album)"},
    {"title": "(Pronounced 'Leh-'nerd 'Skin-'nerd)", "artist": "Lynyrd Skynyrd", "wiki_title": "(Pronounced 'Leh-'nerd 'Skin-'nerd)"},
    {"title": "Aqualung", "artist": "Jethro Tull", "wiki_title": "Aqualung (album)"},
    {"title": "One Nation Under a Groove", "artist": "Funkadelic"},
    {"title": "Let's Get It On", "artist": "Marvin Gaye"},
    {"title": "Boston", "artist": "Boston", "wiki_title": "Boston (album)"},
    {"title": "Call Me", "artist": "Al Green", "wiki_title": "Call Me (Al Green album)"},
    {"title": "Mothership Connection", "artist": "Parliament"},
    {"title": "Frampton Comes Alive!", "artist": "Peter Frampton"},
    {"title": "Fulfillingness' First Finale", "artist": "Stevie Wonder"},
    {"title": "Catch a Fire", "artist": "Bob Marley & the Wailers"},
    {"title": "Honky Chateau", "artist": "Elton John"},
    {"title": "Heart Like a Wheel", "artist": "Linda Ronstadt"},
    {"title": "Rocks", "artist": "Aerosmith", "wiki_title": "Rocks (Aerosmith album)"},
    {"title": "Every Picture Tells a Story", "artist": "Rod Stewart"},
    {"title": "Sweet Baby James", "artist": "James Taylor"},
    {"title": "Bat Out of Hell", "artist": "Meat Loaf", "wiki_title": "Bat Out of Hell (album)"},
    {"title": "Bad Girls", "artist": "Donna Summer", "wiki_title": "Bad Girls (Donna Summer album)"},
    {"title": "Highway to Hell", "artist": "AC/DC"},
    {"title": "Parallel Lines", "artist": "Blondie"},
    {"title": "Trans-Europe Express", "artist": "Kraftwerk"},
    {"title": "Tea for the Tillerman", "artist": "Cat Stevens"},
    {"title": "Something/Anything?", "artist": "Todd Rundgren"},
    {"title": "Band on the Run", "artist": "Paul McCartney & Wings"},
    {"title": "3 + 3", "artist": "The Isley Brothers", "wiki_title": "3 + 3 (album)"},
    {"title": "Eat a Peach", "artist": "The Allman Brothers Band"},
    {"title": "Dreamboat Annie", "artist": "Heart"},
    {"title": "The Cars", "artist": "The Cars", "wiki_title": "The Cars (album)"},
    {"title": "Electric Warrior", "artist": "T. Rex"},
    {"title": "Darkness on the Edge of Town", "artist": "Bruce Springsteen"},
    {"title": "Running on Empty", "artist": "Jackson Browne"},
    {"title": "Alive!", "artist": "KISS", "wiki_title": "Alive! (Kiss album)"},
    {"title": "Fleetwood Mac", "artist": "Fleetwood Mac", "wiki_title": "Fleetwood Mac (album)"},
    {"title": "Rocket to Russia", "artist": "Ramones"},
    {"title": "New York Dolls", "artist": "New York Dolls", "wiki_title": "New York Dolls (album)"},
    {"title": "Damn the Torpedoes", "artist": "Tom Petty and the Heartbreakers"},
    {"title": "Rust Never Sleeps", "artist": "Neil Young & Crazy Horse"},
    {"title": "Close to You", "artist": "The Carpenters", "wiki_title": "Close to You (Carpenters album)"},
    {"title": "I'm Still in Love with You", "artist": "Al Green", "wiki_title": "I'm Still in Love with You (Al Green album)"},
    {"title": "Tumbleweed Connection", "artist": "Elton John"},
    {"title": "Workingman's Dead", "artist": "Grateful Dead"},
    {"title": "Maggot Brain", "artist": "Funkadelic"},
    {"title": "Close to the Edge", "artist": "Yes"},
    {"title": "The B-52's", "artist": "The B-52's", "wiki_title": "The B-52's (album)"},
    {"title": "Fresh", "artist": "Sly and the Family Stone", "wiki_title": "Fresh (Sly and the Family Stone album)"},
    {"title": "Houses of the Holy", "artist": "Led Zeppelin"},
    {"title": "Young, Gifted and Black", "artist": "Aretha Franklin", "wiki_title": "Young, Gifted and Black (Aretha Franklin album)"},
    {"title": "Burnin'", "artist": "Bob Marley and the Wailers", "wiki_title": "Burnin' (album)"},
    {"title": "L.A. Woman", "artist": "The Doors"},
    {"title": "Sad Wings of Destiny", "artist": "Judas Priest"},
    {"title": "That's the Way of the World", "artist": "Earth, Wind & Fire"},
    {"title": "Transformer", "artist": "Lou Reed"},
    {"title": "For Your Pleasure", "artist": "Roxy Music"},
    {"title": "Curtis", "artist": "Curtis Mayfield", "wiki_title": "Curtis (album)"},
    {"title": "There Goes Rhymin' Simon", "artist": "Paul Simon"},
    {"title": "Nightbirds", "artist": "LaBelle"},
    {"title": "Music of My Mind", "artist": "Stevie Wonder"},
    {"title": "Aladdin Sane", "artist": "David Bowie"},
    {"title": "Entertainment!", "artist": "Gang of Four"},
    {"title": "Outlandos d'Amour", "artist": "The Police"},
    {"title": "Talking Heads: 77", "artist": "Talking Heads"},
    {"title": "Pretzel Logic", "artist": "Steely Dan"},
    {"title": "The Basement Tapes", "artist": "Bob Dylan", "wiki_title": "The Basement Tapes"},
    {"title": "Master of Reality", "artist": "Black Sabbath"},
    {"title": "Some Girls", "artist": "The Rolling Stones", "wiki_title": "Some Girls (album)"},
    {"title": "Tubular Bells", "artist": "Mike Oldfield"},
    {"title": "Al Green Gets Next to You", "artist": "Al Green"},
    {"title": "The Wild, the Innocent & the E Street Shuffle", "artist": "Bruce Springsteen"},
    {"title": "Led Zeppelin III", "artist": "Led Zeppelin"},
    {"title": "Desire", "artist": "Bob Dylan", "wiki_title": "Desire (Bob Dylan album)"},
    {"title": "Grievous Angel", "artist": "Gram Parsons"},
    {"title": "Night Moves", "artist": "Bob Seger & the Silver Bullet Band", "wiki_title": "Night Moves (Bob Seger album)"},
    {"title": "461 Ocean Boulevard", "artist": "Eric Clapton"},
    {"title": "Station to Station", "artist": "David Bowie"},
    {"title": "More Songs About Buildings and Food", "artist": "Talking Heads"},
    {"title": "Queen II", "artist": "Queen"},
    {"title": "2112", "artist": "Rush", "wiki_title": "2112 (album)"},
    {"title": "Bryter Layter", "artist": "Nick Drake"},
    {"title": "Sail Away", "artist": "Randy Newman", "wiki_title": "Sail Away (Randy Newman album)"},
    {"title": "Look-Ka Py Py", "artist": "The Meters"},
    {"title": "Berlin", "artist": "Lou Reed", "wiki_title": "Berlin (Lou Reed album)"},
    {"title": "Tonight's the Night", "artist": "Neil Young", "wiki_title": "Tonight's the Night (Neil Young album)"},
    {"title": "Another Green World", "artist": "Brian Eno"},
    {"title": "Roxy Music", "artist": "Roxy Music", "wiki_title": "Roxy Music (album)"},
    {"title": "Back Stabbers", "artist": "The O'Jays"},
    {"title": "Pink Moon", "artist": "Nick Drake"},
    {"title": "Regatta de Blanc", "artist": "The Police"},
    {"title": "Autobahn", "artist": "Kraftwerk", "wiki_title": "Autobahn (album)"},
    {"title": "Late for the Sky", "artist": "Jackson Browne"},
    {"title": "52nd Street", "artist": "Billy Joel"},
    {"title": "Breakfast in America", "artist": "Supertramp"},
    {"title": "Animals", "artist": "Pink Floyd", "wiki_title": "Animals (Pink Floyd album)"},
    {"title": "Natty Dread", "artist": "Bob Marley & the Wailers"},
    {"title": "Selling England by the Pound", "artist": "Genesis"},
    {"title": "Raw Power", "artist": "Iggy and the Stooges"},
    {"title": "Fear of Music", "artist": "Talking Heads"},
    {"title": "Paul Simon", "artist": "Paul Simon", "wiki_title": "Paul Simon (album)"},
    {"title": "Slowhand", "artist": "Eric Clapton"},
    {"title": "Loaded", "artist": "The Velvet Underground", "wiki_title": "Loaded (The Velvet Underground album)"},
    {"title": "Country Life", "artist": "Roxy Music"},
    {"title": "The Pretender", "artist": "Jackson Browne", "wiki_title": "The Pretender (Jackson Browne album)"},
    {"title": "The Modern Lovers", "artist": "The Modern Lovers", "wiki_title": "The Modern Lovers (album)"},
    {"title": "Armed Forces", "artist": "Elvis Costello and the Attractions"},
    {"title": "Heroes", "artist": "David Bowie", "wiki_title": "\"Heroes\" (David Bowie album)"},
    {"title": "Here, My Dear", "artist": "Marvin Gaye"},
    {"title": "Radio City", "artist": "Big Star"},
    {"title": "Q: Are We Not Men? A: We Are Devo!", "artist": "Devo"},
    {"title": "Metal Box", "artist": "Public Image Ltd."},
    {"title": "At Budokan", "artist": "Cheap Trick", "wiki_title": "Cheap Trick at Budokan"},
    {"title": "Pink Flag", "artist": "Wire"},
    {"title": "Thick as a Brick", "artist": "Jethro Tull"},
    {"title": "Back in the USA", "artist": "MC5"},
    {"title": "Band of Gypsys", "artist": "Jimi Hendrix"},
    {"title": "Here Come the Warm Jets", "artist": "Brian Eno"},
    {"title": "I Want to See the Bright Lights Tonight", "artist": "Richard and Linda Thompson"},
    {"title": "#1 Record", "artist": "Big Star"},
    {"title": "Bad Company", "artist": "Bad Company", "wiki_title": "Bad Company (album)"},
    {"title": "Tago Mago", "artist": "Can"},
    {"title": "Risqué", "artist": "Chic", "wiki_title": "Risqué (album)"},
    {"title": "12 Songs", "artist": "Randy Newman"},
    {"title": "Brothers and Sisters", "artist": "The Allman Brothers Band"},
    {"title": "In Color", "artist": "Cheap Trick", "wiki_title": "In Color (Cheap Trick album)"},
    {"title": "The World Is a Ghetto", "artist": "War", "wiki_title": "The World Is a Ghetto (album)"},
    {"title": "The Long Run", "artist": "Eagles"},
    {"title": "The Lamb Lies Down on Broadway", "artist": "Genesis"},
    {"title": "Mott", "artist": "Mott the Hoople", "wiki_title": "Mott (album)"},
    {"title": "Chicago V", "artist": "Chicago"},
    {"title": "Billion Dollar Babies", "artist": "Alice Cooper"},
    {"title": "Fly Like an Eagle", "artist": "Steve Miller Band"},
    {"title": "Destroyer", "artist": "KISS", "wiki_title": "Destroyer (Kiss album)"},
    {"title": "Suicide", "artist": "Suicide", "wiki_title": "Suicide (Suicide album)"},


]
